name: Build and Push Image to Github Container Registry

on:
  push:
    branches:
      - main
    paths:
    - 'Dockerfile'
    - '.github/workflows/build_images.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: keycloak
jobs:
  image_to_gcr:
    strategy:
      matrix:
        keycloak_version: [22.0.4]
        dev_dependencies: ["tar gzip", "tar gzip maven-openjdk17 nodejs npm"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - if: matrix.dev_dependencies == 'tar gzip'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            "KEYCLOAK_VERSION=${{ matrix.keycloak_version }}"
            "DEV_DEPENDECIES=${{ matrix.dev_dependencies }}"
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ matrix.keycloak_version }}-base
          labels: ${{ steps.meta.outputs.labels }}
      - if: matrix.dev_dependencies == 'tar gzip maven-openjdk17 nodejs npm'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            "KEYCLOAK_VERSION:=${{ matrix.keycloak_version }}"
            "DEV_DEPENDECIES:=${{ matrix.dev_dependencies }}"
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ matrix.keycloak_version }}-full
          labels: ${{ steps.meta.outputs.labels }}